<a href="https://colab.research.google.com/github/Apolo5102/GyA---Grupo-4/blob/main/AYUDA4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df_duro_last = pd.read_excel('/content/drive/MyDrive/Shareddrives/gestion &almacenamiento/2025-01/USF2 Duro Last Credit Master.xlsx',
                          sheet_name= 'DURO LAST Credit Master', skiprows= 4, usecols="A:AX")
df_fsbp = pd.read_excel('/content/drive/MyDrive/Shareddrives/gestion &almacenamiento/2025-01/USF2 FSBP Credit Master.xlsx',
                          sheet_name= 'FSBP Credit Master File', skiprows= 4, usecols="A:Z")
df_ses = pd.read_excel('/content/drive/MyDrive/Shareddrives/gestion &almacenamiento/2025-01/USF2 GACO-SES Credit Master.xlsx',
                          sheet_name= 'SES Credit Master', skiprows= 4, usecols="A:U")
df_gaco = pd.read_excel('/content/drive/MyDrive/Shareddrives/gestion &almacenamiento/2025-01/USF2 GACO-SES Credit Master.xlsx',
                          sheet_name= '22520 Sales Tax Credit GACO', skiprows= 4, usecols="A:T")
df_negativos = pd.read_excel('/content/drive/MyDrive/Shareddrives/gestion &almacenamiento/2025-01/1 NEGATIVE TAX MASTER FILE - ALL US COMPANIES.xlsx',
                          sheet_name= 'HBE NEGATIVE TAX', skiprows= 6, usecols="A:AJ")
facturas_pagables = pd.read_csv('/content/drive/MyDrive/Shareddrives/gestion &almacenamiento/Facturas_pagables/facturas_pagables.csv')

ledger_february = pd.read_csv('/content/drive/MyDrive/Shareddrives/gestion &almacenamiento/LEDGER FEBRUARY 2025.csv')

/usr/local/lib/python3.11/dist-packages/openpyxl/worksheet/_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)
<ipython-input-3-f35d08823f5f>:13: DtypeWarning: Columns (2,18) have mixed types. Specify dtype option on import or set low_memory=False.
  ledger_february = pd.read_csv('/content/drive/MyDrive/Shareddrives/gestion &almacenamiento/LEDGER FEBRUARY 2025.csv')

In [ ]:
print("df_duro_last:")
print(df_duro_last.columns)
print("\ndf_fsbp:")
print(df_fsbp.columns)
print("\ndf_ses:")
print(df_ses.columns)
print("\ndf_gaco:")
print(df_gaco.columns)
print("\ndf_negativos:")
print(df_negativos.columns)
print("\nfacturas_pagables:")
print(facturas_pagables.columns)

In [23]:
facturas_pagables

,state,county,city,invoice_number,fuente,o2c_review_level
0,AL,Tuscaloosa,Northport,737582,duro last,city
1,KS,Shawnee,Topeka,761842,duro last,city
2,MS,Rankin,NaN,91845367,fsbp,county
3,MS,Rankin,NaN,91803934,fsbp,county
4,MS,Rankin,NaN,91830724,fsbp,county
5,MS,Rankin,NaN,91842505,fsbp,county
6,MS,Rankin,NaN,91798188,fsbp,county
7,MS,Rankin,NaN,91798187,fsbp,county
8,MO,Greene,Springfield,754423,duro last,city
9,NE,Hall,Grand Island,91875507,fsbp,city
10,NY,Dutchess,Unincorporated Areas,91819546,fsbp,bourough
11,NY,Dutchess,Unincorporated Areas,91819547,fsbp,bourough
12,NY,Westchester,Yonkers,91628433,negatives,bourough
13,NY,Westchester,Yonkers,79241,negatives,bourough
14,NY,Westchester,Yonkers,753613,duro last,bourough
15,OH,NaN,NaN,766100,duro last,state
16,OH,NaN,NaN,764515,duro last,state
17,OH,NaN,NaN,776553,duro last,state
18,TX,Brazoria,Angleton,780177,duro last,city
19,TX,Brazoria,Angleton,779478,duro last,city
20,TX,Brazoria,Angleton,782739,duro last,city
21,TX,Brazoria,Angleton,779055,duro last,city
22,UT,Weber,Ogden,91826548,fsbp,city
23,WI,Barron,NaN,91809802,fsbp,county
24,WI,Barron,NaN,91809803,fsbp,county

In [11]:
fecha_uso_actual = "2025-01"

In [32]:
# Diccionario que mapea cada fuente con su DataFrame y la columna de invoice number
fuentes_map = {
    "duro last": (df_duro_last, "ORIGINAL Invoice", "PERIOD USED"),
    "fsbp": (df_fsbp, "Invoice", "Period Used"),
    "ses": (df_ses, "Invoice #", "Period Used"),
    "gaco": (df_gaco, "Invoice #", "Period Used"),
    "negatives": (df_negativos, "Document Number", "Return Period Used")
}
# Crear un DataFrame vacío para almacenar las modificaciones
facturas_modificadas = pd.DataFrame()

# Iterar sobre cada fila de facturas_pagables
for index, row in facturas_pagables.iterrows():
    invoice_number = row["invoice_number"]
    fuente = row["fuente"]

    # Lista de posibles DataFrames a modificar
    if fuente == "fsbp":
        df_fsbp.loc[df_fsbp['Invoice'] == invoice_number, 'Period Used'] = fecha_uso_actual
        facturas_modificadas = pd.concat([facturas_modificadas, df_fsbp.loc[df_fsbp['Invoice'] == invoice_number]])
    elif fuente == "ses":
        df_ses.loc[df_ses['Invoice #'] == invoice_number, 'Period Used'] = fecha_uso_actual
        facturas_modificadas = pd.concat([facturas_modificadas, df_ses.loc[df_ses['Invoice #'] == invoice_number]])
    elif fuente == "gaco":
        df_gaco.loc[df_gaco['Invoice #'] == invoice_number, 'Period Used'] = fecha_uso_actual
        facturas_modificadas = pd.concat([facturas_modificadas, df_gaco.loc[df_gaco['Invoice #'] == invoice_number]])
    elif fuente == "negatives":
        df_negativos.loc[df_negativos['Document Number'] == invoice_number, 'Return Period Used'] = fecha_uso_actual
        facturas_modificadas = pd.concat([facturas_modificadas, df_negativos.loc[df_negativos['Document Number'] == invoice_number]])
    elif fuente == "duro last":
        df_duro_last.loc[df_duro_last['ORIGINAL Invoice'] == invoice_number, 'PERIOD USED'] = fecha_uso_actual
        facturas_modificadas = pd.concat([facturas_modificadas, df_duro_last.loc[df_duro_last['ORIGINAL Invoice'] == invoice_number]])
    else:
        print(f"Fuente no reconocida: {fuente}")

# Mostrar el DataFrame con todas las facturas modificadas
facturas_modificadas

,PERIOD USED,EXPIRATION DATE,SPECIALS INVOICE DATE,SPECIALS INV#,ORIGINAL TAX REPORTING PERIOD,Co,Whs,WarehouseDescription,Warehouse City,Whse ST,...,Total Tax Rate,State Tax Amount,County Tax Amount,City Tax Amount,District Tax Amount,Total Tax Amount,Status of Tax - If Not Yet Applied,Usage Notes,OriginalPostingDate - Original Billing Document Date,OriginalBillingDoc - Original Invoice
2358,2025-01,2027-05-19,2024-05,76462.0,2024-04,1.0,X,WAREHOUSE X - TEXAS TX,CARROLLTON,TX,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2973,2025-01,2027-10-24,2025-01,80220.0,2024-09,1.0,I,WAREHOUSE I - IOWA IA,SIGOURNEY,IA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8638,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8288,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8616,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8601,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8285,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8284,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2892,2025-01,2027-08-19,2025-01,80548.0,2024-07,1.0,X,WAREHOUSE X - TEXAS TX,CARROLLTON,TX,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2947,2025-01,2027-08-19,2025-01,80584.0,2024-07,1.0,X,WAREHOUSE X - TEXAS TX,CARROLLTON,TX,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8937,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8402,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8389,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
371,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.08875,-38.88,-14.58,-29.16,-3.65,-86.27,NOT Suspended in OneSource Compliance,NaN,NaN,NaN
480,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.08875,-57.07,0,-64.21,-5.35,-126.63,NOT Suspended in OneSource Compliance,NaN,2024-11-04 00:00:00,79241.0
2766,2025-01,2027-08-19,2024-09,78571.0,2024-07,1.0,MA,WAREHOUSE MA - MASSACHUSETS,Ludlow,MA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3060,2025-01,2028-10-22,2025-01,80323.0,2024-09,1.0,A,WAREHOUSE A - DUROLAST 525 DL,SAGINAW,MI,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3057,2025-01,2028-10-22,2025-01,80324.0,2024-09,1.0,A,WAREHOUSE A - DUROLAST 525 DL,SAGINAW,MI,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3038,2025-01,2028-12-22,2025-01,784910.0,2024-11,1.0,D,WAREHOUSE D - INSPECTOR TRUCK,SAGINAW,MI,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2884,2025-01,2029-01-19,2024-12,80044.0,2024-12,1.0,X,WAREHOUSE X - TEXAS TX,CARROLLTON,TX,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2958,2025-01,2029-01-19,2025-01,80312.0,2024-12,1.0,DS,DROPSHIP WAREHOUSE,SAGINAW,MI,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2934,2025-01,2029-02-19,2025-01,80425.0,2025-01,1.0,X,WAREHOUSE X - TEXAS TX,CARROLLTON,TX,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2883,2025-01,2029-01-19,2024-12,80043.0,2024-12,1.0,X,WAREHOUSE X - TEXAS TX,CARROLLTON,TX,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8388,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8822,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8724,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [26]:
df_duro_last.loc[df_duro_last['ORIGINAL Invoice'] == 737582]

,PERIOD USED,EXPIRATION DATE,SPECIALS INVOICE DATE,SPECIALS INV#,ORIGINAL TAX REPORTING PERIOD,Co,Whs,WarehouseDescription,Warehouse City,Whse ST,...,STATE RATE,COUNTY RATE,CITY RATE,DISTRICT RATE,TAXABLE AMOUNT,STATE TAX,COUNTY TAX,CITY TAX,DISTRICT TAX,TOTAL TAX
2358,2025-01,2027-05-19,2024-05,76462.0,2024-04,1,X,WAREHOUSE X - TEXAS TX,CARROLLTON,TX,...,0.04,0.03,0.03,0.0,-24480.0,-979.2,-734.4,-734.4,0.0,-2448.0

In [30]:
df_negativos.loc[df_negativos['Document Number'] == 91628433]

,Jurisdiction Name (State Only),Return Period Used,Return Period Posted,Expiration Date - Please extend the formula,Tax Type,Data Source,Company Name,Co Role,Doc Curr,Doc Date - Line,...,Total Tax Rate,State Tax Amount,County Tax Amount,City Tax Amount,District Tax Amount,Total Tax Amount,Status of Tax - If Not Yet Applied,Usage Notes,OriginalPostingDate - Original Billing Document Date,OriginalBillingDoc - Original Invoice
371,New York,2025-01,2022-11-01,ADD INFO IN COLUMN AI & AJ,Sales,FSBP,"Holcim Solutions and Products US, LLC",Sales,USD,2022-11-01 00:00:00,...,0.08875,-38.88,-14.58,-29.16,-3.65,-86.27,NOT Suspended in OneSource Compliance,NaN,NaN,NaN

In [ ]:
df_duro_last.to_excel('df_duro_last.xlsx', index=False)