<a href="https://colab.research.google.com/github/Apolo5102/GyA---Grupo-4/blob/main/EDA_enero.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Extraccion de los datos a Data frame

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
Duro_last = pd.read_excel('/content/drive/MyDrive/Shareddrives/gestion &almacenamiento/2025-01/USF2 Duro Last Credit Master.xlsx',
                          sheet_name= 'DURO LAST Credit Master', skiprows= 4, usecols="A:AX")

In [ ]:
FSBP = pd.read_excel('/content/drive/MyDrive/Shareddrives/gestion &almacenamiento/2025-01/USF2 FSBP Credit Master.xlsx',
                          sheet_name= 'FSBP Credit Master File', skiprows= 4, usecols="A:Z")

In [ ]:
SES = pd.read_excel('/content/drive/MyDrive/Shareddrives/gestion &almacenamiento/2025-01/USF2 GACO-SES Credit Master.xlsx',
                          sheet_name= 'SES Credit Master', skiprows= 4, usecols="A:U")

In [ ]:
Gaco = pd.read_excel('/content/drive/MyDrive/Shareddrives/gestion &almacenamiento/2025-01/USF2 GACO-SES Credit Master.xlsx',
                          sheet_name= '22520 Sales Tax Credit GACO', skiprows= 4, usecols="A:T")

In [ ]:
Negativos = pd.read_excel('/content/drive/MyDrive/Shareddrives/gestion &almacenamiento/2025-01/1 NEGATIVE TAX MASTER FILE - ALL US COMPANIES.xlsx',
                          sheet_name= 'HBE NEGATIVE TAX', skiprows= 6, usecols="A:AJ")

/usr/local/lib/python3.11/dist-packages/openpyxl/worksheet/_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)

In [ ]:
Ledger = pd.read_csv('/content/drive/MyDrive/Shareddrives/gestion &almacenamiento/LEDGER JANUARY 2025.csv',delimiter= ",")

<ipython-input-8-abd049be21f0>:1: DtypeWarning: Columns (18) have mixed types. Specify dtype option on import or set low_memory=False.
  Ledger = pd.read_csv('/content/drive/MyDrive/Shareddrives/gestion &almacenamiento/LEDGER JANUARY 2025.csv',delimiter= ",")

In [ ]:
Duro_last.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3073 entries, 0 to 3072
Data columns (total 50 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   PERIOD USED                    2482 non-null   object
 1   EXPIRATION DATE                3073 non-null   datetime64[ns]
 2   SPECIALS INVOICE DATE          3073 non-null   object
 3   SPECIALS INV#                  3072 non-null   float64
 4   ORIGINAL TAX REPORTING PERIOD  3073 non-null   object
 5   Co                             3073 non-null   int64
 6   Whs                            3073 non-null   object
 7   WarehouseDescription           3073 non-null   object
 8   Warehouse City                 2962 non-null   object
 9   Whse ST                        2962 non-null   object
 10  Whse Zip                       2962 non-null   float64
 11  ORIGINAL InvoiceDate           3073 non-null   datetime64[ns]
 12  ORIGINAL Invoice               3073 non-null   int64
 13  ORIGINAL Order                 3073 non-null   int64
 14  Customer                       3073 non-null   int64
 15  CustomerName                   3073 non-null   object
 16  ShipToAddress1                 3073 non-null   object
 17  ShipToAddress2                 2769 non-null   object
 18  ShipToCity                     3073 non-null   object
 19  ShipToST                       3073 non-null   object
 20  ShipToZip                      3071 non-null   object
 21  Carrier                        2783 non-null   object
 22  TaxSuffix                      3073 non-null   object
 23  Tax Code                       2962 non-null   object
 24  Tax Amt                        1247 non-null   float64
 25  Tax %                          2412 non-null   float64
 26  Tax Description                2962 non-null   object
 27  Tax Base                       1354 non-null   float64
 28  TotalItems                     1344 non-null   float64
 29  ItemTax                        1344 non-null   float64
 30  Freight                        1344 non-null   float64
 31  SpecialCharges                 1344 non-null   float64
 32  FreightSpcChrgTax              1344 non-null   float64
 33  TotalTax                       3073 non-null   float64
 34  TotalInvoice                   1211 non-null   float64
 35  Comment                        206 non-null    object
 36  CREDIT / DEBIT                 3073 non-null   object
 37  ORIGINAL TAXABLE STATE         3073 non-null   object
 38  ORIGINAL TAXABLE COUNTY        3073 non-null   object
 39  ORIGINAL TAXABLE CITY          3073 non-null   object
 40  STATE RATE                     3073 non-null   float64
 41  COUNTY RATE                    3073 non-null   float64
 42  CITY RATE                      3073 non-null   float64
 43  DISTRICT RATE                  3073 non-null   float64
 44  TAXABLE AMOUNT                 2150 non-null   float64
 45  STATE TAX                      3073 non-null   float64
 46  COUNTY TAX                     3073 non-null   float64
 47  CITY TAX                       3073 non-null   float64
 48  DISTRICT TAX                   3073 non-null   float64
 49  TOTAL TAX                      3073 non-null   float64
dtypes: datetime64[ns](2), float64(22), int64(4), object(22)
memory usage: 1.2+ MB

In [ ]:
FSBP.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9016 entries, 0 to 9015
Data columns (total 26 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Period Used             8010 non-null   object
 1   Expiration Date         8871 non-null   object
 2   Posting Period          9016 non-null   datetime64[ns]
 3   Ship To Account Number  8998 non-null   float64
 4   Payer Number            9000 non-null   object
 5   Account Name            8956 non-null   object
 6   Invoice                 9012 non-null   object
 7   Invoice Date            9013 non-null   object
 8   9-Digit Zip Code        9001 non-null   object
 9   ZIP                     9016 non-null   object
 10  GEO                     7824 non-null   object
 11  State                   9016 non-null   object
 12  County                  8974 non-null   object
 13  City                    8960 non-null   object
 14  District                5056 non-null   object
 15  State Tax               8896 non-null   object
 16  County Tax              8559 non-null   object
 17  City Tax                8538 non-null   object
 18  District Tax            2859 non-null   float64
 19  Total Tax               9016 non-null   float64
 20  Correction Number       8843 non-null   object
 21  Correction Date         8818 non-null   object
 22  Comments / Explanation  8943 non-null   object
 23  Tax Zip Code            2495 non-null   object
 24  Tax Type Code           1978 non-null   object
 25  Location #              2051 non-null   float64
dtypes: datetime64[ns](1), float64(4), object(21)
memory usage: 1.8+ MB

In [ ]:
SES.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 21 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Period Used            3 non-null      datetime64[ns]
 1   Expiration Date        10 non-null     datetime64[ns]
 2   Posting Period         10 non-null     datetime64[ns]
 3   Tax Type               10 non-null     object
 4   Voucher                0 non-null      float64
 5   Desc                   0 non-null      float64
 6   Invoice #              10 non-null     int64
 7   Debit                  10 non-null     float64
 8   Credit                 10 non-null     int64
 9   Import Amount          10 non-null     float64
 10  Customer               0 non-null      float64
 11  Customer Name          10 non-null     object
 12  Original Invoice #     0 non-null      float64
 13  Original Invoice Date  10 non-null     datetime64[ns]
 14  Address                10 non-null     object
 15  Tax City               10 non-null     object
 16  Tax State              10 non-null     object
 17  Tax Zip                10 non-null     int64
 18  Tax Zip + 4 GEO        10 non-null     int64
 19  Location #             0 non-null      float64
 20  Comments               10 non-null     object
dtypes: datetime64[ns](4), float64(7), int64(4), object(6)
memory usage: 1.8+ KB

In [ ]:
Gaco.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 287 entries, 0 to 286
Data columns (total 20 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Period Used            257 non-null    object
 1   Expiration Date        287 non-null    datetime64[ns]
 2   Posting Period         287 non-null    object
 3   Tax Type               287 non-null    object
 4   Voucher                277 non-null    object
 5   Desc                   1 non-null      object
 6   Invoice #              287 non-null    object
 7   Debit                  287 non-null    float64
 8   Credit                 287 non-null    float64
 9   Import Amount          287 non-null    float64
 10  Customer               287 non-null    int64
 11  Customer Name          287 non-null    object
 12  Original Invoice #     285 non-null    object
 13  Original Invoice Date  285 non-null    datetime64[ns]
 14  Address                285 non-null    object
 15  Tax City               287 non-null    object
 16  Tax State              287 non-null    object
 17  Tax Zip                287 non-null    int64
 18  Tax Zip + 4 GEO        267 non-null    float64
 19  Location #             13 non-null     object
dtypes: datetime64[ns](2), float64(4), int64(2), object(12)
memory usage: 45.0+ KB

In [ ]:
Negativos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 484 entries, 0 to 483
Data columns (total 36 columns):
 #   Column                                                Non-Null Count  Dtype
---  ------                                                --------------  -----
 0   Jurisdiction Name (State Only)                        484 non-null    object
 1   Return Period Used                                    262 non-null    object
 2   Return Period Posted                                  484 non-null    datetime64[ns]
 3   Expiration Date - Please extend the formula           484 non-null    object
 4   Tax Type                                              484 non-null    object
 5   Data Source                                           484 non-null    object
 6   Company Name                                          480 non-null    object
 7   Co Role                                               477 non-null    object
 8   Doc Curr                                              481 non-null    object
 9   Doc Date - Line                                       481 non-null    object
 10  Fiscal Date                                           481 non-null    object
 11  Document Number                                       482 non-null    object
 12  Line No                                               307 non-null    object
 13  Taxable State                                         484 non-null    object
 14  Taxable County                                        476 non-null    object
 15  Taxable City                                          472 non-null    object
 16  Taxable Postal Code                                   421 non-null    float64
 17  Taxable Geo Code
(+ 4)                                156 non-null    object
 18  Total Gross Amount                                    374 non-null    float64
 19  Exempt Amount                                         340 non-null    object
 20  Tax Basis Doc Amount                                  371 non-null    float64
 21  Sum Tax Amount                                        484 non-null    float64
 22  State Tax Rate                                        469 non-null    float64
 23  County Tax Rate                                       470 non-null    float64
 24  City Tax Rate                                         455 non-null    float64
 25  District Tax Rate                                     455 non-null    float64
 26  Total Tax Rate                                        392 non-null    float64
 27  State Tax Amount                                      452 non-null    float64
 28  County Tax Amount                                     451 non-null    object
 29  City Tax Amount                                       445 non-null    object
 30  District Tax Amount                                   408 non-null    object
 31  Total Tax Amount                                      484 non-null    float64
 32  Status of Tax - If Not Yet Applied                    396 non-null    object
 33  Usage Notes                                           150 non-null    object
 34  OriginalPostingDate - Original Billing Document Date  250 non-null    object
 35  OriginalBillingDoc - Original Invoice                 249 non-null    float64
dtypes: datetime64[ns](1), float64(12), object(23)
memory usage: 136.3+ KB

In [ ]:
Ledger.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100654 entries, 0 to 100653
Data columns (total 35 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Journal Id             100654 non-null  int64
 1   Region                 100654 non-null  object
 2   Tax Location           4260 non-null    float64
 3    Tax Level             100654 non-null  object
 4   Tax Authority          100654 non-null  object
 5   Tax Type               100654 non-null  object
 6   Tax Name               100654 non-null  object
 7   Gross                  100654 non-null  float64
 8   Exemptions             100654 non-null  float64
 9   Taxable                100654 non-null  float64
 10  Rate                   100654 non-null  float64
 11  Tax                    100654 non-null  float64
 12  Tax Collected          100654 non-null  float64
 13  Over(Under) Collected  100654 non-null  float64
 14  Charge Name            0 non-null       float64
 15  Quantity               100654 non-null  int64
 16  Charge Rate            100654 non-null  float64
 17  Charge                 100654 non-null  float64
 18  Credit Name            10976 non-null   object
 19  Credit                 100654 non-null  float64
 20  Calc                   100654 non-null  int64
 21  Invoice #              100654 non-null  object
 22  Item #                 2714 non-null    object
 23  Business Location      100654 non-null  object
 24  Tax Area Code          100654 non-null  int64
 25  County                 100654 non-null  object
 26  City                   100654 non-null  object
 27  Districts              46195 non-null   object
 28  Collecting Level       100654 non-null  object
 29  Collecting Authority   100654 non-null  object
 30  Tax Code               100654 non-null  object
 31  Department Code        0 non-null       float64
 32  Vendor Number          2714 non-null    object
 33   Customer Number       28491 non-null   float64
 34  Description            100654 non-null  object
dtypes: float64(14), int64(4), object(17)
memory usage: 26.9+ MB

# Preguntas disparadoras



*   Cuantos creditos quedan por usar (vacios) y cuanto suman en total?
*   Estados con la mayor cantidad de creditos por usar?
*   Identificar el nivel al que se pagan impuestos(estado, condado o ciudad)
*   Realizar tabla dinamica de Ledger para permitir comparacion automatica con los creditos disponibles

In [ ]:
Duro_last.columns

Index(['PERIOD USED', 'EXPIRATION DATE', 'SPECIALS INVOICE DATE',
       'SPECIALS INV#', 'ORIGINAL TAX REPORTING PERIOD', 'Co', 'Whs',
       'WarehouseDescription', 'Warehouse City', 'Whse ST', 'Whse Zip',
       'ORIGINAL InvoiceDate', 'ORIGINAL Invoice', 'ORIGINAL Order',
       'Customer', 'CustomerName', 'ShipToAddress1', 'ShipToAddress2',
       'ShipToCity', 'ShipToST', 'ShipToZip', 'Carrier', 'TaxSuffix',
       'Tax Code', 'Tax Amt', 'Tax %', 'Tax Description', 'Tax Base',
       'TotalItems', 'ItemTax', 'Freight', 'SpecialCharges',
       'FreightSpcChrgTax', 'TotalTax', 'TotalInvoice', 'Comment',
       'CREDIT / DEBIT', 'ORIGINAL TAXABLE STATE', 'ORIGINAL TAXABLE COUNTY',
       'ORIGINAL TAXABLE CITY', 'STATE RATE', 'COUNTY RATE', 'CITY RATE',
       'DISTRICT RATE', 'TAXABLE AMOUNT', 'STATE TAX', 'COUNTY TAX',
       'CITY TAX', 'DISTRICT TAX', 'TOTAL TAX'],
      dtype='object')

In [ ]:
Duro_last = Duro_last[['PERIOD USED','EXPIRATION DATE','ORIGINAL Invoice','ORIGINAL TAXABLE STATE', 'ORIGINAL TAXABLE COUNTY',
                        'ORIGINAL TAXABLE CITY', 'STATE TAX', 'COUNTY TAX',
                        'CITY TAX', 'TOTAL TAX' ]]

Duro_last.head(5)

,PERIOD USED,EXPIRATION DATE,ORIGINAL Invoice,ORIGINAL TAXABLE STATE,ORIGINAL TAXABLE COUNTY,ORIGINAL TAXABLE CITY,STATE TAX,COUNTY TAX,CITY TAX,TOTAL TAX
0,2024-03,2026-05-19,674993,ALABAMA,ETOWAH,RAINBOW CITY,-276.96,-69.24,-346.20,-692.40
1,2024-03,2026-05-19,676994,ALABAMA,ETOWAH,RAINBOW CITY,-26.02,-6.51,-32.53,-65.06
2,2024-03,2026-05-19,677574,ALABAMA,ETOWAH,RAINBOW CITY,-9.40,-2.35,-11.75,-23.50
3,2024-03,2026-06-19,678797,ALABAMA,ETOWAH,RAINBOW CITY,-3.58,-0.90,-4.48,-8.96
4,2024-03,2026-06-19,679529,ALABAMA,ETOWAH,RAINBOW CITY,-0.24,-0.06,-0.30,-0.60

In [ ]:
FSBP.columns

Index(['Period Used', 'Expiration Date', 'Posting Period',
       'Ship To Account Number', 'Payer Number', 'Account Name', 'Invoice',
       'Invoice Date', '9-Digit Zip Code', 'ZIP', 'GEO', 'State', 'County',
       'City', 'District', 'State Tax', 'County Tax', 'City Tax',
       'District Tax', 'Total Tax', 'Correction Number', 'Correction Date',
       'Comments / Explanation', 'Tax Zip Code', 'Tax Type Code',
       'Location #'],
      dtype='object')

In [ ]:
FSBP = FSBP[['Period Used', 'Expiration Date','Invoice','State', 'County',
       'City', 'State Tax', 'County Tax', 'City Tax', 'Total Tax']]

FSBP.head(5)

,Period Used,Expiration Date,Invoice,State,County,City,State Tax,County Tax,City Tax,Total Tax
0,2021-11-01 00:00:00,2024-05-19 00:00:00,91196074,TX,EL PASO,EL PASO,-2640.77,-211.3,-633.73,-3485.80
1,2021-11-01 00:00:00,2024-05-19 00:00:00,91196071,TX,EL PASO,EL PASO,-1425.91,-114.08,-342.19,-1882.18
2,2021-11-01 00:00:00,2024-05-19 00:00:00,91196064,TX,EL PASO,EL PASO,-845.06,-67.6,-202.81,-1115.47
3,2021-11-01 00:00:00,2024-07-19 00:00:00,91397923,IL,MCLEAN,BLOOMINGTON,-1048.6,0,0,-1048.60
4,2021-11-01 00:00:00,2025-09-19 00:00:00,91418120,TX,EL PASO,EL PASO,-627.47,-252.52,-153.04,-1033.03

In [ ]:
SES.columns

Index(['Period Used', 'Expiration Date', 'Posting Period', 'Tax Type',
       'Voucher', 'Desc', 'Invoice #', 'Debit', 'Credit', 'Import Amount',
       'Customer ', 'Customer Name', 'Original Invoice #',
       'Original Invoice Date', 'Address', 'Tax City', 'Tax State', 'Tax Zip',
       'Tax Zip + 4 GEO', 'Location #', 'Comments'],
      dtype='object')

In [ ]:
SES = SES[['Period Used', 'Expiration Date','Invoice #', 'Tax State','Tax City','Tax Zip',
            'Tax Zip + 4 GEO', 'Import Amount']]

SES.head(10)

,Period Used,Expiration Date,Invoice #,Tax State,Tax City,Tax Zip,Tax Zip + 4 GEO,Import Amount
0,NaT,2028-03-22,38067,WA,KENT,98031,1938,-2408.86
1,NaT,2028-03-22,38068,WA,KENT,98031,1938,-4585.41
2,NaT,2028-03-22,38069,WA,KENT,98031,1938,-4949.00
3,NaT,2028-03-22,38070,WA,KENT,98031,1938,-5252.00
4,NaT,2028-03-22,38071,WA,KENT,98031,1938,-2805.45
5,NaT,2028-03-22,38072,WA,KENT,98031,1938,-3008.30
6,NaT,2028-03-22,38073,WA,KENT,98031,1938,-5151.00
7,2024-05-31,2028-03-22,38075,WA,KENT,98031,1938,-2291.92
8,2024-07-31,2028-03-22,38076,WA,KENT,98031,1938,-4242.00
9,2024-07-31,2028-03-22,38432,WA,KENT,98031,1938,-4386.00

In [ ]:
Gaco.columns

Index(['Period Used', 'Expiration Date', 'Posting Period', 'Tax Type',
       'Voucher', 'Desc', 'Invoice #', 'Debit', 'Credit', 'Import Amount',
       'Customer ', 'Customer Name', 'Original Invoice #',
       'Original Invoice Date', 'Address', 'Tax City', 'Tax State', 'Tax Zip',
       'Tax Zip + 4 GEO', 'Location #'],
      dtype='object')

In [ ]:
Gaco = Gaco[['Period Used', 'Expiration Date','Invoice #', 'Tax State','Tax City','Tax Zip',
              'Tax Zip + 4 GEO','Import Amount']]

Gaco.head(10)

,Period Used,Expiration Date,Invoice #,Tax State,Tax City,Tax Zip,Tax Zip + 4 GEO,Import Amount
0,2021-11-01 00:00:00,2024-05-27,CR010368,CT,NORWALK,6851,NaN,-1309.40
1,2021-11-01 00:00:00,2024-03-19,CR010411,FL,FORT MYERS,33905,NaN,-98.49
2,2021-11-01 00:00:00,2024-04-19,CR010412,FL,FORT MYERS,33905,NaN,-84.42
3,2021-11-01 00:00:00,2024-06-27,CR010349,MA,NORTHBOROUGH,1532,NaN,-1718.37
4,2021-11-01 00:00:00,2025-06-19,CR010365,MD,SPARROWS POINT,21219,1751.0,-1055.40
5,2021-11-01 00:00:00,2025-06-19,CR010346,MD,SPARROWS POINT,21219,1751.0,-2390.13
6,2021-11-01 00:00:00,2025-06-19,CR010348,MD,SPARROWS POINT,21219,1751.0,-758.28
7,2021-11-01 00:00:00,2025-07-19,CR010339,MD,SPARROWS POINT,21219,1751.0,-824.82
8,2021-11-01 00:00:00,2025-06-19,CR010347,NJ,BRIDGEWATER,8807,2909.0,-2850.83
9,2021-11-01 00:00:00,2025-09-19,CR010456,NJ,Cloucester City,8030,2409.0,-721.46

In [ ]:
Negativos.columns

Index(['Return Period Used', 'Expiration Date - Please extend the formula',
       'Document Number', 'Data Source', 'Taxable State', 'Taxable County',
       'Taxable City', 'State Tax Amount', 'County Tax Amount',
       'City Tax Amount', 'Total Tax Amount'],
      dtype='object')

In [ ]:
Negativos = Negativos[['Return Period Used','Expiration Date - Please extend the formula','Document Number',
                       'Data Source','Taxable State', 'Taxable County', 'Taxable City','State Tax Amount','County Tax Amount', 'City Tax Amount','Total Tax Amount']]

Negativos.head()

,Return Period Used,Expiration Date - Please extend the formula,Document Number,Data Source,Taxable State,Taxable County,Taxable City,State Tax Amount,County Tax Amount,City Tax Amount,Total Tax Amount
0,2022-10-31 00:00:00,2025-03-20 00:00:00,91496175,FSBP,Alabama,Lee (RDS),Opelika (RDS),0.0,-171.73,-686.91,-858.64
1,2022-10-31 00:00:00,2025-03-20 00:00:00,91496645,FSBP,Alabama,Lee (RDS),Opelika (RDS),0.0,-170.64,-682.56,-853.20
2,2022-10-31 00:00:00,2025-07-31 00:00:00,2A571f-1660330739-32463,SES,ALABAMA,NaN,NaN,-184.0,-184,0,-414.00
3,2022-10-31 00:00:00,2025-07-31 00:00:00,2A9387-1661875160-32584\n,SES,ALABAMA,NaN,NaN,-368.0,-368,0,-828.00
4,NaN,2026-03-20 00:00:00,91651445,FSBP,ALABAMA,Cullman,Cullman,-2620.8,-2948.4,-327.6,-5896.80

In [ ]:
#Falta period used
Duro_last.describe().T

,count,mean,min,25%,50%,75%,max,std
EXPIRATION DATE,3073,2027-08-22 19:31:57.735112192,2025-05-19 00:00:00,2027-02-19 00:00:00,2027-08-19 00:00:00,2028-02-19 00:00:00,2029-02-22 00:00:00,NaN
ORIGINAL Invoice,3073.0,709184.659941,66693.0,699630.0,725430.0,750981.0,783761.0,112010.891191
STATE TAX,3073.0,-897.945264,-39138.80315,-895.91,-213.36,-32.09875,0.0,2032.194765
COUNTY TAX,3073.0,-106.891709,-5690.13,-45.83,0.0,0.0,0.0,366.373114
CITY TAX,3073.0,-198.981498,-19685.19685,-66.936,0.0,0.0,0.0,758.865109
TOTAL TAX,3073.0,-1227.225419,-58824.0,-1217.77,-286.94,-46.18,-0.01,2869.26654

In [ ]:
Duro_last.describe(include= 'O').T

                        count unique         top freq
PERIOD USED              2482     11     2024-03  671
ORIGINAL TAXABLE STATE   3073     43       TEXAS  820
ORIGINAL TAXABLE COUNTY  3073    406      DALLAS  237
ORIGINAL TAXABLE CITY    3073    619  CARROLLTON  219

In [ ]:
#Problema de fechas
FSBP.describe().T

,count,mean,std,min,25%,50%,75%,max
Total Tax,9016.0,-960.607433,1592.004368,-32108.12,-1105.0,-622.78,-155.0925,9661.68

In [ ]:
FSBP.describe(include = 'object').T

                count unique                   top  freq
Period Used      8010     73   2021-11-01 00:00:00   749
Expiration Date  8871    248   2025-06-19 00:00:00   380
Invoice          9012   8682              91424608     5
State            9016     42                    IL  1507
County           8974    421             BALTIMORE   322
City             8960    690  UNINCORPORATED AREAS  2419
State Tax        8896   4850                     0  1268
County Tax       8559   2316                     0  4337
City Tax         8538   1718                     0  4924

In [ ]:
SES.describe().T

,count,mean,min,25%,50%,75%,max,std
Period Used,3,2024-07-10 16:00:00,2024-05-31 00:00:00,2024-06-30 12:00:00,2024-07-31 00:00:00,2024-07-31 00:00:00,2024-07-31 00:00:00,NaN
Expiration Date,10,2028-03-22 00:00:00,2028-03-22 00:00:00,2028-03-22 00:00:00,2028-03-22 00:00:00,2028-03-22 00:00:00,2028-03-22 00:00:00,NaN
Invoice #,10.0,38107.3,38067.0,38069.25,38071.5,38074.5,38432.0,114.124737
Tax Zip,10.0,98031.0,98031.0,98031.0,98031.0,98031.0,98031.0,0.0
Tax Zip + 4 GEO,10.0,1938.0,1938.0,1938.0,1938.0,1938.0,1938.0,0.0
Import Amount,10.0,-3907.994,-5252.0,-4858.1025,-4314.0,-2856.1625,-2291.92,1160.373609

In [ ]:
SES.describe(include = 'object').T

          count unique   top freq
Tax State    10      1    WA   10
Tax City     10      1  KENT   10

In [ ]:
Gaco.describe().T

,count,mean,min,25%,50%,75%,max,std
Expiration Date,287,2026-05-30 17:18:36.376306688,2023-04-19 00:00:00,2025-09-07 12:00:00,2026-07-31 00:00:00,2027-04-19 00:00:00,2028-11-22 00:00:00,NaN
Tax Zip,287.0,48366.54007,1104.0,28803.0,44139.0,75262.0,98926.0,28897.808785
Tax Zip + 4 GEO,267.0,3842.438202,16.0,1943.0,3124.0,5788.5,9779.0,2428.142789
Import Amount,287.0,-1678.852578,-37221.59,-2073.825,-632.44,-133.83,1347.57,3097.776793

In [ ]:
# Falta period used to date
Gaco.describe(include = 'object').T

            count unique                  top freq
Period Used   257     36  2022-08-31 00:00:00   27
Invoice #     287    287             CR010368    1
Tax State     287     32                   FL   49
Tax City      287    141                CAMAS   15

In [ ]:
Negativos.describe().T

,count,mean,std,min,25%,50%,75%,max
State Tax Amount,452.0,-733.419490,1676.175013,-15672.2,-479.47,-425.710,-20.4150,2052.0
Total Tax Amount,484.0,-1199.022946,2202.422647,-15672.2,-1396.62,-692.375,-72.3925,2394.0

In [ ]:
Negativos.describe(include = 'object').T

,count,unique,top,freq
Return Period Used,262,75,2021-11-01 00:00:00,61
Expiration Date - Please extend the formula,484,69,2026-04-20 00:00:00,57
Document Number,482,381,91447730,11
Data Source,484,6,FSBP,418
Taxable State,484,30,COLORADO,184
Taxable County,476,85,Clay,95
Taxable City,472,81,Liberty,95
County Tax Amount,451,169,0,94
City Tax Amount,445,160,0,117

**Se identifica como FSBP tiene la mayor cantidad de formatos incorrectos, teniendo como texto varias fechas y valores de taxes necesarios para el desarrollo del proyecto**

In [ ]:
#Correcion de fechas Duro_Last

Duro_last['PERIOD USED'] = pd.to_datetime(Duro_last['PERIOD USED'],errors= 'coerce')

In [ ]:
Duro_last.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3073 entries, 0 to 3072
Data columns (total 10 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   PERIOD USED              2482 non-null   datetime64[ns]
 1   EXPIRATION DATE          3073 non-null   datetime64[ns]
 2   ORIGINAL Invoice         3073 non-null   int64
 3   ORIGINAL TAXABLE STATE   3073 non-null   object
 4   ORIGINAL TAXABLE COUNTY  3073 non-null   object
 5   ORIGINAL TAXABLE CITY    3073 non-null   object
 6   STATE TAX                3073 non-null   float64
 7   COUNTY TAX               3073 non-null   float64
 8   CITY TAX                 3073 non-null   float64
 9   TOTAL TAX                3073 non-null   float64
dtypes: datetime64[ns](2), float64(4), int64(1), object(3)
memory usage: 240.2+ KB

In [ ]:
#Correccion de fecha period used para FSBP y valores numericos para los niveles de pago de impuestos

FSBP['Period Used'] = pd.to_datetime(FSBP['Period Used'],errors= 'coerce')
FSBP['Expiration Date'] = pd.to_datetime(FSBP['Expiration Date'],errors= 'coerce')
FSBP['State Tax'] = pd.to_numeric(FSBP['State Tax'],errors= 'coerce')
FSBP['County Tax'] = pd.to_numeric(FSBP['County Tax'],errors= 'coerce')
FSBP['City Tax'] = pd.to_numeric(FSBP['City Tax'],errors= 'coerce')

In [ ]:
FSBP.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9016 entries, 0 to 9015
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Period Used      7924 non-null   datetime64[ns]
 1   Expiration Date  8612 non-null   datetime64[ns]
 2   Invoice          9012 non-null   object
 3   State            9016 non-null   object
 4   County           8974 non-null   object
 5   City             8960 non-null   object
 6   State Tax        8803 non-null   float64
 7   County Tax       8137 non-null   float64
 8   City Tax         7907 non-null   float64
 9   Total Tax        9016 non-null   float64
dtypes: datetime64[ns](2), float64(4), object(4)
memory usage: 704.5+ KB

In [ ]:
Gaco['Period Used'] = pd.to_datetime(Gaco['Period Used'],errors= 'coerce')

In [ ]:
Gaco.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 287 entries, 0 to 286
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Period Used      254 non-null    datetime64[ns]
 1   Expiration Date  287 non-null    datetime64[ns]
 2   Invoice #        287 non-null    object
 3   Tax State        287 non-null    object
 4   Tax City         287 non-null    object
 5   Tax Zip          287 non-null    int64
 6   Tax Zip + 4 GEO  267 non-null    float64
 7   Import Amount    287 non-null    float64
dtypes: datetime64[ns](2), float64(2), int64(1), object(3)
memory usage: 18.1+ KB

In [ ]:
Duro_last.to_csv('Duro_last.csv', index= False, date_format= "%Y-%m-%d")
FSBP.to_csv('FSBP.csv', index= False, date_format= "%Y-%m-%d")
SES.to_csv('SES.csv', index= False, date_format= "%Y-%m-%d")
Gaco.to_csv('Gaco.csv', index= False, date_format= "%Y-%m-%d")
Negativos.to_csv('Negativos.csv', index= False, date_format= "%Y-%m-%d")

# Duro Last

In [ ]:
DL = pd.read_csv('/content/Duro_last.csv',parse_dates=['PERIOD USED', 'EXPIRATION DATE'])

In [ ]:
DL.columns

Index(['PERIOD USED', 'EXPIRATION DATE', 'ORIGINAL Invoice',
       'ORIGINAL TAXABLE STATE', 'ORIGINAL TAXABLE COUNTY',
       'ORIGINAL TAXABLE CITY', 'STATE TAX', 'COUNTY TAX', 'CITY TAX',
       'TOTAL TAX'],
      dtype='object')

In [ ]:
DL.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3073 entries, 0 to 3072
Data columns (total 10 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   PERIOD USED              2482 non-null   datetime64[ns]
 1   EXPIRATION DATE          3073 non-null   datetime64[ns]
 2   ORIGINAL Invoice         3073 non-null   int64
 3   ORIGINAL TAXABLE STATE   3073 non-null   object
 4   ORIGINAL TAXABLE COUNTY  3073 non-null   object
 5   ORIGINAL TAXABLE CITY    3073 non-null   object
 6   STATE TAX                3073 non-null   float64
 7   COUNTY TAX               3073 non-null   float64
 8   CITY TAX                 3073 non-null   float64
 9   TOTAL TAX                3073 non-null   float64
dtypes: datetime64[ns](2), float64(4), int64(1), object(3)
memory usage: 240.2+ KB

In [ ]:
duplicados_factura_DL = DL[DL.duplicated(subset=["ORIGINAL Invoice"], keep=False)]
duplicados_factura_DL

,PERIOD USED,EXPIRATION DATE,ORIGINAL Invoice,ORIGINAL TAXABLE STATE,ORIGINAL TAXABLE COUNTY,ORIGINAL TAXABLE CITY,STATE TAX,COUNTY TAX,CITY TAX,TOTAL TAX
66,2024-03-01,2026-07-19,68057,GEORGIA,FORSYTH,CUMMING,-31.800000,-23.850000,0.000000,-55.65
67,2024-03-01,2026-07-19,68057,GEORGIA,FORSYTH,CUMMING,-31.800000,-23.850000,0.000000,-55.65
145,2024-03-01,2026-08-19,691377,INDIANA,GRANT,GAS CITY,-930.920000,0.000000,0.000000,-930.92
146,2024-03-01,2026-08-19,691377,INDIANA,GRANT,GAS CITY,-930.920000,0.000000,0.000000,-930.92
165,2024-03-01,2026-12-19,712973,INDIANA,LAWRENCE,MITCHELL,-8189.480000,0.000000,0.000000,-8189.48
...,...,...,...,...,...,...,...,...,...,...
2890,NaT,2027-09-19,756201,FLORIDA,CLAY,ORANGE PARK,-18.008000,-4.502000,0.000000,-22.51
2891,NaT,2027-09-19,756201,FLORIDA,CLAY,ORANGE PARK,-18.008000,-4.502000,0.000000,-22.51
2892,NaT,2027-08-19,754423,MISSOURI,GREENE,SPRINGFIELD,-39138.803150,0.000000,-19685.196850,-58824.00
2947,NaT,2027-08-19,754423,MISSOURI,GREENE,SPRINGFIELD,-391.388031,0.000000,-196.851969,-588.24
2979,NaT,2026-08-19,690504,ALABAMA,RANDOLPH,WOODLAND,-146.652308,-91.657692,0.000000,-238.31

In [ ]:
conteo_DL = duplicados_factura_DL['ORIGINAL Invoice'].value_counts()
conteo_DL

ORIGINAL Invoice
756201    3
68057     2
69867     2
753864    2
758125    2
760487    2
760488    2
771001    2
771003    2
771004    2
762385    2
779809    2
690504    2
66856     2
707186    2
691377    2
680373    2
680376    2
681062    2
68092     2
694435    2
750869    2
751173    2
747653    2
714244    2
727384    2
769615    2
753632    2
713107    2
712350    2
676736    2
712973    2
713838    2
720453    2
698444    2
697612    2
685207    2
708081    2
687179    2
681452    2
708413    2
710700    2
687458    2
735336    2
687459    2
687460    2
685643    2
720969    2
712750    2
737148    2
739546    2
713810    2
701018    2
733651    2
707237    2
754423    2
Name: count, dtype: int64

# FSBP

In [ ]:
FS = pd.read_csv('/content/FSBP.csv',parse_dates=['Period Used', 'Expiration Date'])

In [ ]:
FS.columns

Index(['Period Used', 'Expiration Date', 'Invoice', 'State', 'County', 'City',
       'State Tax', 'County Tax', 'City Tax', 'Total Tax'],
      dtype='object')

In [ ]:
FS.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9016 entries, 0 to 9015
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Period Used      7924 non-null   datetime64[ns]
 1   Expiration Date  8612 non-null   datetime64[ns]
 2   Invoice          9012 non-null   object
 3   State            9016 non-null   object
 4   County           8974 non-null   object
 5   City             8960 non-null   object
 6   State Tax        8803 non-null   float64
 7   County Tax       8137 non-null   float64
 8   City Tax         7907 non-null   float64
 9   Total Tax        9016 non-null   float64
dtypes: datetime64[ns](2), float64(4), object(4)
memory usage: 704.5+ KB

In [ ]:
duplicados_factura_FSBP = FS[FS.duplicated(subset=['Invoice'], keep=False)]
duplicados_factura_FSBP

,Period Used,Expiration Date,Invoice,State,County,City,State Tax,County Tax,City Tax,Total Tax
23,2022-03-31,NaT,One Line Tax Correction,UT,JACKSON,UNINCORPORATED AREAS,-807.36,0.00,0.00,-807.36
138,2022-03-31,NaT,One Line Tax Correction,MO,JACKSON,UNINCORPORATED AREAS,-510.55,0.00,0.00,-510.55
142,2022-03-31,NaT,One Line Tax Correction,MO,JACKSON,UNINCORPORATED AREAS,-476.44,0.00,0.00,-476.44
157,2021-11-01,2025-08-22,91410949,OH,HAMILTON,CINCINNATI,-212.75,-75.85,0.00,-288.60
161,2021-11-01,2024-08-14,91412816,ME,ANDROSCOGGIN,UNINCORPORATED AREAS,-255.70,0.00,0.00,-255.70
...,...,...,...,...,...,...,...,...,...,...
8965,NaT,NaT,91819565,IA,DES MOINES,BURLINGTON,-209.76,-34.96,NaN,-244.72
8986,NaT,NaT,91864725,NY,JEFFERSON,UNINCORPORATED AREAS,NaN,-85.63,NaN,-85.63
8987,NaT,NaT,91864725,NY,JEFFERSON,UNINCORPORATED AREAS,-85.63,NaN,NaN,-85.63
9001,NaT,NaT,91871483,CO,EL PASO,COLORADO SPRINGS,-54.00,NaN,NaN,-54.00
9015,NaT,NaT,91869116,UT,SALT LAKE,MILLCREEK,NaN,NaN,-0.34,-0.34

In [ ]:
conteo_FS = duplicados_factura_FSBP['Invoice'].value_counts()
conteo_FS

Invoice
91424608                   5
One Line Tax Correction    4
91410949                   4
91469795                   4
91494749                   4
                          ..
91496434                   2
91500974                   2
91500975                   2
91500941                   2
91864725                   2
Name: count, Length: 302, dtype: int64

# Gaco

**Sin facturas duplicadas**

In [ ]:
G = pd.read_csv('/content/Gaco.csv',parse_dates=['Period Used', 'Expiration Date'])

In [ ]:
G.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 287 entries, 0 to 286
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Period Used      254 non-null    datetime64[ns]
 1   Expiration Date  287 non-null    datetime64[ns]
 2   Invoice #        287 non-null    object
 3   Tax State        287 non-null    object
 4   Tax City         287 non-null    object
 5   Tax Zip          287 non-null    int64
 6   Tax Zip + 4 GEO  267 non-null    float64
 7   Import Amount    287 non-null    float64
dtypes: datetime64[ns](2), float64(2), int64(1), object(3)
memory usage: 18.1+ KB

In [ ]:
duplicados_factura_Gaco = G[G.duplicated(subset=['Invoice #'], keep=False)]
duplicados_factura_Gaco

Empty DataFrame
Columns: [Period Used, Expiration Date, Invoice #, Tax State, Tax City, Tax Zip, Tax Zip + 4 GEO, Import Amount]
Index: []

# SES

**Sin facturas duplicadas**

In [ ]:
SS = pd.read_csv('/content/SES.csv',parse_dates=['Period Used', 'Expiration Date'])

In [ ]:
SS.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Period Used      3 non-null      datetime64[ns]
 1   Expiration Date  10 non-null     datetime64[ns]
 2   Invoice #        10 non-null     int64
 3   Tax State        10 non-null     object
 4   Tax City         10 non-null     object
 5   Tax Zip          10 non-null     int64
 6   Tax Zip + 4 GEO  10 non-null     int64
 7   Import Amount    10 non-null     float64
dtypes: datetime64[ns](2), float64(1), int64(3), object(2)
memory usage: 772.0+ bytes

In [ ]:
duplicados_factura_SES = SS[SS.duplicated(subset=['Invoice #'], keep=False)]
duplicados_factura_SES

Empty DataFrame
Columns: [Period Used, Expiration Date, Invoice #, Tax State, Tax City, Tax Zip, Tax Zip + 4 GEO, Import Amount]
Index: []

# Negativos

In [ ]:
NN = pd.read_csv('/content/Negativos.csv',parse_dates=['Return Period Used', 'Expiration Date - Please extend the formula'])

In [ ]:
NN.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 484 entries, 0 to 483
Data columns (total 11 columns):
 #   Column                                       Non-Null Count  Dtype
---  ------                                       --------------  -----
 0   Return Period Used                           262 non-null    object
 1   Expiration Date - Please extend the formula  484 non-null    object
 2   Document Number                              482 non-null    object
 3   Data Source                                  484 non-null    object
 4   Taxable State                                484 non-null    object
 5   Taxable County                               476 non-null    object
 6   Taxable City                                 472 non-null    object
 7   State Tax Amount                             452 non-null    float64
 8   County Tax Amount                            451 non-null    object
 9   City Tax Amount                              445 non-null    object
 10  Total Tax Amount                             484 non-null    float64
dtypes: float64(2), object(9)
memory usage: 41.7+ KB

In [ ]:
duplicados_factura_Negativos = NN[NN.duplicated(subset=['Document Number'], keep=False)]
duplicados_factura_Negativos

,Return Period Used,Expiration Date - Please extend the formula,Document Number,Data Source,Taxable State,Taxable County,Taxable City,State Tax Amount,County Tax Amount,City Tax Amount,Total Tax Amount
23,2022-01-31 00:00:00,2025-01-20 00:00:00,91479584,FSBP,Arkansas,Pulaski,North Little Rock,NaN,NaN,NaN,-2617.01
24,2022-01-31 00:00:00,2025-01-20 00:00:00,91479584,FSBP,Arkansas,Pulaski,North Little Rock,NaN,NaN,NaN,-149.85
25,2022-01-31 00:00:00,2025-01-20 00:00:00,91479584,FSBP,Arkansas,Pulaski,North Little Rock,NaN,NaN,NaN,-291.20
26,2022-01-31 00:00:00,2025-01-20 00:00:00,91479584,FSBP,Arkansas,Pulaski,North Little Rock,NaN,NaN,NaN,-453.24
27,2022-01-31 00:00:00,2025-01-20 00:00:00,91479584,FSBP,Arkansas,Pulaski,North Little Rock,NaN,NaN,NaN,-77.73
...,...,...,...,...,...,...,...,...,...,...,...
420,2021-12-31 00:00:00,2024-12-20 00:00:00,91463085,FSBP,Tennessee,Davidson,Nashville,-21.00,-6.75,0,-29.25
421,2021-12-31 00:00:00,2024-12-20 00:00:00,91466562,FSBP,Tennessee,Davidson,Nashville,853.12,274.22,0,1188.28
422,2021-12-31 00:00:00,2024-12-20 00:00:00,91466562,FSBP,Tennessee,Davidson,Nashville,853.12,274.22,0,1188.28
423,2021-12-31 00:00:00,2024-12-20 00:00:00,91466562,FSBP,Tennessee,Davidson,Nashville,5.74,1.85,0,8.00
424,2021-12-31 00:00:00,2024-12-20 00:00:00,91466562,FSBP,Tennessee,Davidson,Nashville,5.74,1.85,0,8.00

In [ ]:
conteo_NN = duplicados_factura_Negativos['Document Number'].value_counts()
conteo_NN

Document Number
91447730      11
91655225       8
91479584       7
1600701979     7
91576010       6
91577339       6
91655655       4
91655217       4
91655219       4
91655221       4
91655222       4
91655226       4
91655227       4
91655228       4
91466562       4
91576616       4
91576615       3
91565733       3
91655194       2
91655209       2
91463085       2
91461873       2
102226         2
91630240       2
91584359       2
91579677       2
91468376       2
5105879033     2
91655629       2
91655211       2
91655207       2
91654772       2
91655205       2
91655203       2
91655201       2
91655199       2
91655197       2
91661222       2
91481340       2
91654760       2
91654762       2
91654764       2
91654766       2
91654768       2
91654770       2
91654758       2
Name: count, dtype: int64